### ISSUE TITLE
Multiple accounts give error in HA

### ISSUE THREAD

**Issue by Sholofly** [Sholofly/arrisdcx960#10]
**Describe the bug**
When a second account is added, the startup of the Arris component gives a key error

**To Reproduce**
1. Go to integrations 
2. add a second arris implementation
3. restart home assistant
4. See error in log: 
```
2021-09-17 16:03:35 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up arris_dcx960 platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/arris_dcx960/media_player.py", line 67, in async_setup_entry
    api = hass.data[DOMAIN][entry.entry_id][API]
KeyError: 'f6864349f63e36682f3a862b126cfbc2'
```

**Expected behavior**
No erros and an available player

**Screenshots**

**Logging**
Enable debug logging and add your log. DO NOT SHARE SENSITIVE DATA SUCH AS PASSWORDS AND ACCOUNT INFO!
You can enable logging by setting up the logging component in HA as follows:
```yaml
logger:
  default: warning
  logs:
    arris_dcx960: debug
```

**Additional context**
Snippets wehere the problem looks to be:

__init__.py:
```python
async def async_setup_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Set up arrisdcx960 from a config entry."""
    api = ArrisDCX960(
        entry.data[CONF_USERNAME],
        entry.data[CONF_PASSWORD],
        COUNTRY_CODES[entry.data[CONF_COUNTRY_CODE]],
    )
    await hass.async_add_executor_job(api.connect)
    hass.data[DOMAIN] = {}
    hass.data[DOMAIN][entry.entry_id] = {
        API: api,
        CONF_OMIT_CHANNEL_QUALITY: entry.data[CONF_OMIT_CHANNEL_QUALITY],
        CONF_USERNAME: entry.data[CONF_USERNAME],
    }
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)

    return True
```
media_player.py:
```python
async def async_setup_entry(
    hass: HomeAssistantType,
    entry: ConfigEntry, 
    async_add_entities: AddEntitiesCallback
) -> None:
    """Setup platform"""
    players = []
    api = hass.data[DOMAIN][entry.entry_id][API]
    omit_channel_quality = hass.data[DOMAIN][entry.entry_id][CONF_OMIT_CHANNEL_QUALITY]
    for box in api.settop_boxes.values():
        players.append(ArrisDCX960MediaPlayer(box, api, omit_channel_quality))
    async_add_entities(players, True)
```

**Comment by Sholofly** [comment]
@richardtrinks, I was able to reproduce your issue. No solution found yet.

**Comment by richardtrinks** [comment]
I reinstalled the integration and added both accounts.
But since this afternoon I saw that problem again, but I'm glad you were able to reproduce it too.

If there is a solution for it, I am recommended to test it.

**Comment by Sholofly** [comment]
@richardtrinks found the issue. Very stupid one :) Please update the component. Note that (in the latest beta at least) sometimes after a reboot some accounts give an invalid credentials error. Don't know the exact reason for it.
