### ISSUE TITLE
Error: cannot import name 'AddEntitiesCallback' from 'homeassistant.helpers.entity_platform

### ISSUE THREAD

**Issue by zheffie** [Sholofly/arrisdcx960#11]
Hi @Sholofly,

I'm attempting to install your integration for Telenet. I installed the HACS and HA integration and configured my credentials. It successfully creates the Arris integration, but no device/entity is created, Log shows below error:

```Logger: homeassistant.setup
Source: setup.py:310
First occurred: 8:11:11 (1 occurrences)
Last logged: 8:11:11

Unable to prepare setup for platform arris_dcx960.media_player: Platform not found (cannot import name 'AddEntitiesCallback' from 'homeassistant.helpers.entity_platform' (/usr/src/homeassistant/homeassistant/helpers/entity_platform.py)).
```

my HA version is 2021.5.5.

Any idea what could be wrong?

**Comment by zheffie** [comment]
Upgraded HA version to latest version. Seems resolved now

**Comment by Sholofly** [comment]
I was already typing an answer :). Glad to hear it is resolved.  I will update the hacs file with the correct version of HA. Please feel free to leave any feedback or feature requests!
