### ISSUE TITLE
Google Home

### ISSUE THREAD

**Issue by famko09** [Sholofly/arrisdcx960#13]
I have installed the integration for the Arris DCX960 in HA. It's showing in the UI, I can switch it on and off, so fa so good. But it is not showing in Google Home, so I can't use Google Assistant to control the Arris DCX960 with voice control. Is this possible?
Other devices do show up in Google Home.
Thanks for your help

**Comment by Sholofly** [comment]
Hi,

It should work like the other media players. Please check if you've exposed
it to your Google home.

Op vr 1 okt. 2021 12:52 schreef famko09 ***@***.***>:
