### ISSUE TITLE
"Unable to load config flow"  error while adding integration on the HA integration page

### ISSUE THREAD

**Issue by moostmartijn** [Sholofly/arrisdcx960#17]
I installed the integration trough HACS and tried to add the integration on the HA integration page but I received an error:

" 
Fout
Config flow kon niet geladen worden
"

Unable to load config flow

Log: 
2021-11-12 18:47:21 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration arris_dcx960: cannot import name 'FlowResult' from 'homeassistant.data_entry_flow' (/usr/src/homeassistant/homeassistant/data_entry_flow.py)

Version HA:
2021.4.6 (yes, not the latest because of some problems with the new Tuya integration which doesn't support my curtain motor yet)

I re-installed the integration and re-started HA sever times, but it did not work.

**Comment by Sholofly** [comment]
Hi @moostmartijn, Sorry for the late response. I suspect that my compatibility data is not right. I am trying to figure out what the minimum version is that the component supports. Sorry for any inconvenience

**Comment by Sholofly** [comment]
@moostmartijn Found it already, you'll need at least version 2021.5.0.
