### ISSUE TITLE
Doesn't Show in HACS Search

### ISSUE THREAD

**Issue by joshward9182** [Sholofly/arrisdcx960#18]
**Describe the bug**
Repository is not found when searching for it in HACS.
HACS recognises that the repository already exists, if I try to add it as a custom repository, but the Integration is not found.

**To Reproduce**
1. Go to HACS
2. Click on 'Integrations'
3. Click on 'Add repository'
3. Search for 'ArrisDCX960'
4. Repository not found.

**Expected behavior**
Expected to be able to find the Integration repository for installation.

**Screenshots**
![Screenshot_20211124-154121__01.jpg](https://user-images.githubusercontent.com/69898979/143270628-69fc2a8f-c009-4e60-a2b8-68b5820b8cb6.jpg)

![Screenshot_20211124-145514__01.jpg](https://user-images.githubusercontent.com/69898979/143271261-b4649c49-3a2f-4eea-a20b-7ac20af6d436.jpg)

**Logging**
N/A

**Additional context**
Home Assistant Information:
version | core-2021.11.1
host_os | Home Assistant OS 6.6
supervisor_version | supervisor-2021.10.8

**Comment by Sholofly** [comment]
Hi @joshward9182, I can't explain why this ahappens to you. Are you sure you don't have the repo already installed? Maybe you have to reboot HA first to clear the repo-cache?

**Comment by joshward9182** [comment]
Thanks for the reply @Sholofly.

I definitely don't have it installed already.
I have attempted a full reboot (power cycle) of the RPi which doesn't appear to have solved the issue.

I have also asked, on a Facebook group, if anyone else was able to find it and had a response from someone saying it is found correctly for them. 

HACS also comes up with the "New Repositories", so appears to detect & update the repo's correctly..

Weird issue..

**Comment by AyloKieran** [comment]
Hey both, I am experiencing the same issue here

version | core-2021.11.5
host_os | Home Assistant OS 6.6
supervisor_version | supervisor-2021.10.8

**Comment by joshward9182** [comment]
@AyloKieran kind of nice to know I'm not the only one..
I wonder if it's a HACS issue..

I updated from HACS 1.17.2 to 1.18.0 earlier, didn't seem to fix it.

When I get time, I might do a fresh install and restore a snapshot as I also seem to be having issues with loading Add-on logs.
See if that helps.

**Comment by Sholofly** [comment]
I guess it's an HACS issue, but I am not sure. There has been a major update yesterday, does updating fixes the problem?

**Comment by p83ot** [comment]
I have the same issue.
My HACS version is 1.18.0
Under HACS about I see that I have 3 downloaded repositories:
But I only see 2 of them in the integration tab. (see pictures below).
Mayby the third one is the invisible arrisDCX960
I've updated HACS to version 1.18.0 some days ago. Now I don't see a new upgrade available for HACS.

![image](https://user-images.githubusercontent.com/94972206/144212089-7c7bfc7f-4f7f-474d-ba01-20694ff6e60d.png)
![image](https://user-images.githubusercontent.com/94972206/144212120-fceabff2-00a6-4a8a-9578-6017efb4eae5.png)

**Comment by joshward9182** [comment]
@Sholofly I found my issue.

Under my HACS configuration, I have a 'GB' country filter (see screenshot).
![Screenshot_20211201-134243__01.jpg](https://user-images.githubusercontent.com/69898979/144245529-38744a05-b244-489c-870a-067d70084b26.jpg)

I think it's because your 'hacs.json' file only has 'NL' in the array.

**Comment by p83ot** [comment]
that solved it for me too. Thanks @joshward9182 !
My filter was 'BE'. When I set it to 'ALL' the integration appeared.

**Comment by Sholofly** [comment]
Thanks, I've added the countries.
