### ISSUE TITLE
BREAKING CHANGE in HA 2021.12

### ISSUE THREAD

**Issue by bafplus** [Sholofly/arrisdcx960#19]
Entity media_player.mediabox (<class 'custom_components.arris_dcx960.media_player.ArrisDCX960MediaPlayer'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by Sholofly** [comment]
Resolved in latest version!

**Comment by bafplus** [comment]
Is it? Cause its only fixed in the master branch but latest version still
gives the issue

Op di 7 dec. 2021 om 15:34 schreef Rudolf Offereins <
***@***.***>:

**Comment by Sholofly** [comment]
Have you refreshed hacs, and restarted? It is fixed for me...

Op di 7 dec. 2021 17:11 schreef bafplus ***@***.***>:

**Comment by bafplus** [comment]
Yep worked! Thanks!
