### ISSUE TITLE
audio controls

### ISSUE THREAD

**Issue by bkbartk** [Sholofly/arrisdcx960#2]
Hello Sholofly,

Thank you for this great tool, I didn't notice the other one was deprecated before.
this one works well.
I started creating a remote based on this one
https://github.com/bkbartk/Ziggo-Remote-Control
nog sure is anyone else has done this already.

one question I have at the moment is if it is somehow possible to manage audio control using the ziggo box. I know this isn't the usual case. but I'm just wondering if it would somehow be possible.

**Comment by Sholofly** [comment]
Hi Bart,

Thank you!
I did (officially) deprecate it yesterday so it's not surprising you haven't  noticed before.
The audio controls do control the audio on your television, as far as i know it's not possible to manage audio using your Arris box.
Perhaps you can use a Broadlink RM mini to control your TV audio via RF?

**Comment by StevoNL** [comment]
Hey Bart,

Looking at you're remote control git it seems you have a LG tv? Anyway if your tv has an integration in Home Assistant you can combine different functions from media players to act as one using [Universal Media Player](https://www.home-assistant.io/integrations/universal/). For instance the all the goodies of the arrisdcx960 aka Ziggo Next combined with the volume control from the LG webOS integration (or AndroidTV, Samsung, Bravia, Philips etc)

Btw: Rudolf, still digging the integration, you're a coding saint!

**Comment by Sholofly** [comment]
@StevoNL good suggestion about the media player. Maybe someone can add the possibility to my component to define service calls for the volume controls in the setup. I.e. wen you call the volume up call from my component, then call the volume up from the WebOS component..  do you understand what I mean? I am not able to test it myself because my tv doesn't support WebOS..

Thanks for the compliment about the coding, but I think you're overrating me. I am not a python developer at all and my ziggonext library doesn't meet the standards I use in my daily job as .NET developer. Why are you digging the integration? Can I help you with something?

**Comment by StevoNL** [comment]
@Sholofly I disagree with you there. Home Assistant is DIY making things work together. Your integration focuses on the mediabox. Adding the volume controls from your component means that the config flow will become more complicated if service calls for other devices are involved (maybe even having to add yaml in the config.yaml again). A breaking component then will break yours as well. Home Assistant already caters to the possible needs through the universal media player for users to cater it to their needs (perhaps if someone did they will share their code or make a blueprint).
I'm digging the integration (meaning I like it a lot!), no help needed.
- It's just so satisfying to walk into the room not having to look for the remote first and just saying "Hey Google, stel de televisie in op RTL4" and having it turn on to the correct channel. Or "Hey Google, sluit jij af?" And everything turns off downstairs except for one pilot light and the bedlights in the bedroom are already on.
- I like being able to browse the media library on my phone while my housemates can still watch what's on without a menu overlay. Then when I've selected the recording that we're going to watch it says ".... is gestuurd vanaf Home Assistant". 
Can't beat that! Have a nice day.

**Comment by bkbartk** [comment]
Hello,
thank you both for your response.
I indeed have an LG tv using webos.
this one also is connected to HA. with a working remote.
At the moment I am able to just swap the remote in HA to manage audio, but it would be nice to not have to do that.
If someone would create some implementation for webOS I would be able to test is. I'm not a python developer so I can't help much with that past, Also I don't know how to debug software for HA. for me it's just deploy and test.

I will check if it is possible to connect the remote I created for Ziggo directly to another media import. but yesterday I couldn't find any. Also this will make the remote less general. But I will look into this because it would be nice if it was possible.

**Comment by Sholofly** [comment]
> @Sholofly I disagree with you there. Home Assistant is DIY making things work together. Your integration focuses on the mediabox. Adding the volume controls from your component means that the config flow will become more complicated if service calls for other devices are involved (maybe even having to add yaml in the config.yaml again). A breaking component then will break yours as well. Home Assistant already caters to the possible needs through the universal media player for users to cater it to their needs (perhaps if someone did they will share their code or make a blueprint).

Excellent point. You're right!

> I'm digging the integration (meaning I like it a lot!), no help needed.

Sorry, misread the sentence. Good to hear it is of use!

 
> * It's just so satisfying to walk into the room not having to look for the remote first and just saying "Hey Google, stel de televisie in op RTL4" and having it turn on to the correct channel. Or "Hey Google, sluit jij af?" And everything turns off downstairs except for one pilot light and the bedlights in the bedroom are already on.

How did you activate a command on the (self created?) voice command: "Hey Google, sluit jij af?"?

> * I like being able to browse the media library on my phone while my housemates can still watch what's on without a menu overlay. Then when I've selected the recording that we're going to watch it says ".... is gestuurd vanaf Home Assistant".
>   Can't beat that! Have a nice day.

Nice :)

**Comment by StevoNL** [comment]
> How did you activate a command on the (self created?) voice command: "Hey Google, sluit jij af?"?

Google Routines. Sadly you can only select lights, thermostats and locks natively. To turn off the decoder it's necessary to select "Je eigen opdrachten toevoegen" and then type your otherwise spoken command.  I typed "Schakel tv uit"

**Comment by Sholofly** [comment]
Because it is a function of the remote and not the box I will close this FR. Thanks and feel free to submit more issues or FR in the future!

**Comment by bkbartk** [comment]
thank you both I just wanted to let you know, I managed to connect the  audio to the LG tv.
I tried to make it somehow generic for philips etc. but I actually think the method names are different so those need to be overruled as well. but for now it works.
