### ISSUE TITLE
Option to check if the mediabox is powered on/off

### ISSUE THREAD

**Issue by askmurphy** [Sholofly/arrisdcx960#20]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
 I want to switch a lamp on/off depending of the mediabox is powered on or off.  How can I do that?

**Describe alternatives you've considered**
none

**Additional context**
-

**Comment by Sholofly** [comment]
@askmurphy Merry Christmas! The mediaplayer has a state. Can't you switch the lamp on when the box isn't in the 'off' state?

**Comment by askmurphy** [comment]
> @askmurphy Merry Christmas! The mediaplayer has a state. Can't you switch the lamp on when the box isn't in the 'off' state?

Can't find the state of it, i see a list of channels but no on/off state?

**Comment by askmurphy** [comment]
![image](https://user-images.githubusercontent.com/16864371/147370238-b6366cc3-3bee-4c25-9de7-a908e18ea9b0.png)

**Comment by askmurphy** [comment]
Any ideas?

**Comment by Sholofly** [comment]
![image](https://user-images.githubusercontent.com/901632/147370561-36e15058-045f-472f-878f-9b42e74fab13.png)
one is playing other is off.

**Comment by Sholofly** [comment]
Closed. Requested functionality is already there.
