### ISSUE TITLE
Ziggo Next first time login not working v1.0.11 but does in v1.0.10

### ISSUE THREAD

**Issue by kjw1985** [Sholofly/arrisdcx960#22]
Last week I received my Ziggo Next box and installed this custom integration. Added the integration and filled in the needed information. However my Next box wasn't available in home-assistant. In the logs there was a error present (unfortunately I didn't copied the error). Tried several things by removing the integration and re-adding it, updated HASS to 2021.12.7, downgraded to 2021.12.6 and updated again. However after downgrading the Arrisdcx960 integration to v1.0.10 the Next box became available in HASS.  Upgrading to v1.0.11 via HACS kept the integration working.

**Not working:**
Initial configuration with Home assistant 2021.12.5, 2021.12.6 and 2021.12.7 and Arrisdcx960 v1.0.11
I couldn't reproduce the error I had earlier (tried it by removing the integration and add the integration again). So the information below is based on my search queries and memory.

The error was in bootstrap stating it ended at self.settop_boxes[deviceId].update_settopbox_state(jsonPayload) with a KeyError with the value: 0000F0-HZNSTB-218159673340

**Working**:
Home assistant 2021.12.7 with v1.0.10 will sign in, after that I can upgrade to v1.0.11. 

Hopefully you are able to find the problem based on the minimal error information I gave. If there is anything else I could try please let me know.
#

**Comment by Sholofly** [comment]
Hi @kjw1985 Thank you for your report. Since there's no functional difference between the two versions, it's likely that its a bug that's there for a longer time. I am not able to reproduce it, so I will keep this bug open for a while to see if more people are experiencing the same. Please let me know if you runs into more issues or have feature requests!

**Comment by Sholofly** [comment]
Hi @kjw1985 is everything working fine for you now?

**Comment by kjw1985** [comment]
@Sholofly At the moment is seems to be working fine. Although I must say I'm not using it extensively and the Next box's energy mode isn't set to high. So it is unavailable (as expected). The only issue I had was that it wasn't updating the status for a day, but this might have been the reaction to some network hiccups I created. I will test keep an eye on the integration to see if the 'problem' can be reproduced. 

Do you think it is possible to add the NPOplus app as a source?  What information might we need?

Hass is giving me the following when the Next box is on the NPO app:

```
media_content_type: episode
media_title: NPO
source: NPO
entity_picture_local: /api/media_player_proxy/media_player.mediabox_2?token=<token>&cache=<cache>
play_mode: app
channel: NPO
title: NPO
image: https://cdn.metrological.com/s/apps/com.twentyfouri.npo/1.0.24-e47ad5c/Images/npo-maf-icon.png
device_class: tv
entity_picture: https://cdn.metrological.com/s/apps/com.twentyfouri.npo/1.0.24-e47ad5c/Images/npo-maf-icon.png
```

**Comment by Sholofly** [comment]
Do you have a channel number to open the NPO plus app?

Op do 13 jan. 2022 19:09 schreef kjw1985 ***@***.***>:

**Comment by kjw1985** [comment]
The NPO app is at channel 152. I saw that Prime Video (I don't use this) is on channel 153.

**Comment by Sholofly** [comment]
@kjw1985 I've updated the component. The channels are available in the source list now.
