### ISSUE TITLE
After installing custom component unable to add the integration

### ISSUE THREAD

**Issue by petersmaikel** [Sholofly/arrisdcx960#28]
I have installed the ArrisDCX960 custom component via Hacs

When i than look voor the integration in Home Assistant i'm unable to find it. 
uninstalling and reinstalling the custom component with reboots in between did not solve the issue. 

![image](https://user-images.githubusercontent.com/75754224/158656994-779b9dff-9045-4987-b133-dfe9172c9541.png)
![image](https://user-images.githubusercontent.com/75754224/158657099-785a9510-99e8-420c-9c46-da3f7dd2e66f.png)

Home Assistant version core-2022.3.5
Arris DCX960 v 1.2.0

**Comment by Palitami** [comment]
+1, same issue here

**Comment by Palitami** [comment]
Thanks for the "workaround" with prior version, it's working now

**Comment by th0f** [comment]
What's the workaround? Custom installation?

**Comment by Sholofly** [comment]
Clear the browser cache, check the logs for errors?

**Comment by Sholofly** [comment]
Do you have an Arrix Box?

**Comment by gregbtm** [comment]
I believe so. Its virgin 360. I thought they all were.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by robertwebbe** [comment]
I have the same issue. It works fine on my old Pi. Tried to install it on my my new Pi4 and cannot find the integration after installing in HACS (and rebooting).

**Comment by Sholofly** [comment]
Have you cleared the browsers cache?

**Comment by robertwebbe** [comment]
I'm sorry, you already suggested that in an earlier comment, I did not...
And it worked when I did that. Excellent, thank you very much!

**Comment by Sholofly** [comment]
You're welcome. I'm glad it worked!
