### ISSUE TITLE
New type of EOS box available in Belgium

### ISSUE THREAD

**Issue by WesleyLiekens** [Sholofly/arrisdcx960#29]
Hello,

I would just like to let you know that there is a new version of the tvbox in Belgium
And its not an Arris DCX960 but a Humax 2008C-STB-TN
your integration finds it but it just gives it the wrong brand/type

I have also send this to Jochen Siegenthaler for his homebridge plugin, as I am his Belgium tester

I happen to work for Telenet Belgium so if I can be of any help to you with this please let me know

Mvg Wes

**Comment by Sholofly** [comment]
Thanks for the heads up. Can you inform me what works and what doesn't?

**Comment by WesleyLiekens** [comment]
it seems everything works fine
only seems to get the wrong brand/type

**Comment by Sholofly** [comment]
Do you mean the logo?

Op do 7 apr. 2022 10:23 schreef WesleyLiekens ***@***.***>:

**Comment by WesleyLiekens** [comment]
No. Your integration says the decoder is a dcx960 by arris

But Its a 2008C-STB-TN by Humax

![image](https://user-images.githubusercontent.com/63705562/162275211-05256d18-6bee-4c3a-99f4-34a1d8432a75.jpeg)

**Comment by WesleyLiekens** [comment]
any update on this?

**Comment by Sholofly** [comment]
I'm busy with a great renaming, where this will be a part of. I'm lacking enough time for now..

**Comment by WesleyLiekens** [comment]
ok cool.

**Comment by Sholofly** [comment]
Hi there. This component is not functional anymore. I'm continuing here: https://github.com/Sholofly/lghorizon
For now only Ziggo but I'm trying to connect other providers in the future. I've looked for device info already but still can''t find it in the API
