### ISSUE TITLE
config flow no strings

### ISSUE THREAD

**Issue by golles** [Sholofly/arrisdcx960#3]
First of all congratulations on your new intagration!

While setting up I didn't see any strings in the config flow:
![Screenshot 2021-09-01 at 15 09 41](https://user-images.githubusercontent.com/2211503/131679348-60aac8e3-d995-49a9-bc5e-838677211667.png)

**Comment by Sholofly** [comment]
What's your ui language?

**Comment by golles** [comment]
My HA is set to NL, checked on 2 computers (NL and EN)

**Comment by Sholofly** [comment]
What version is your HA and whta version of my component do you use? You have errors i can't explain ...

**Comment by golles** [comment]
HA: 2021.8.8 (latest) component (dev branch, latest).
Indeed #4 I don't understand myself, I'll try to see myself as well

**Comment by Sholofly** [comment]
Have you tried to reinstall the component?

**Comment by golles** [comment]
I removed it from disk and checked out again with a restart in between and that fixed it, so something went wrong on my side, closing it
