### ISSUE TITLE
New type of EOS box available in The Netherlands

### ISSUE THREAD

**Issue by robertwebbe** [Sholofly/arrisdcx960#31]
I have a Ziggo Mediabox **Next Mini** (Arris VIP5002W-ZG) and it is working on the EOS platform as well. 
The integration knows only one model, the DCX960:

![screenshot](https://tweakers.net/fotoalbum/image/1SGsvIektb0y0NhmwC73p7Si.png)'

Is it possible to recognize this new mediabox and show VIP5002W?

![Next Mini](https://tweakers.net/i/FF4Too2klyT7oZTfnQYPXN4qMCc=/i/2005054304.png)

**Comment by Sholofly** [comment]
@robertwebbe it's only the name of the integration.that doesn't match the box you have. What would be the benefit of changing the name of the integration?

**Comment by robertwebbe** [comment]
@Sholofly 

If I may make a suggestion: I would find it more logical and clearer if the name of the integration were called **Liberty Global**, it runs on this platform. There are now several types using this platform. The DCX960 is no longer the exclusive type.

Is it possible to read the type? Because then you can put DCX960 or VIP5200W.

**Comment by Sholofly** [comment]
All suggestions are more than welcome. Thanks for that. I think Liberty Global is a little too broad for this component, but I know how they call their television division... It was Horizon before, but that name doesn't cover it anymore..

**Comment by Jordenjj** [comment]
@robertwebbe Can you confirm it worked using the mini? I havent been able to found a way to connect.

**Comment by robertwebbe** [comment]
@Jordenjj Yes, I have two mini’s activated. 

I’ve added the first one when I also had a Next. I’ve sent the Next back and this one disappeared from the list. Maybe it doesn’t work for you because you don’t have a Next and it doesn’t work with a blanc list. But this is a wild guess.

**Comment by Jordenjj** [comment]
> @Jordenjj Yes, I have two mini’s activated.
> 
> I’ve added the first one when I also had a Next. I’ve sent the Next back and this one disappeared from the list. Maybe it doesn’t work for you because you don’t have a Next and it doesn’t work with a blanc list. But this is a wild guess.

Strange, that seems unlikely since they're both running the same operating system. To clarify, you've sent the next back but you can still see the next mini now?

**Comment by Sholofly** [comment]
Hi there. This component is not functional anymore. I'm continuing here: https://github.com/Sholofly/lghorizon
For now only Ziggo but I'm trying to connect other providers in the future. The new box is supported too.
