### ISSUE TITLE
Telenet not showing what's playing anymore since today

### ISSUE THREAD

**Issue by sammyke007** [Sholofly/arrisdcx960#37]
**Describe the bug**
Since today my Telenet TVbox stopped showing what channel or recording is currently playing. It shows "playing", but not the channel name or recording anymore? 

**To Reproduce**
Play something on the TVbox and check HASS. 

**Expected behavior**
Show channel name or recording currently playing. 

**Screenshots**
![Screenshot_2022-10-12-22-58-45-08_c3a231c25ed346e59462e84656a70e50.jpg](https://user-images.githubusercontent.com/33524412/195446772-23e3ac47-241c-4854-9a04-9d4cc9414770.jpg)

**Version of the component**
Latest

**Logging**
Enable debug logging and add your log. DO NOT SHARE SENSITIVE DATA SUCH AS PASSWORDS AND ACCOUNT INFO!
You can enable logging by setting up the logging component in HA as follows:
```yaml
logger:
  default: warning
  logs:
    arris_dcx960: debug
```

**Additional context**

**Comment by sammyke007** [comment]
All of a sudden it revived... I'll test again tomorrow!

![Screenshot_2022-10-12-23-23-30-77_c3a231c25ed346e59462e84656a70e50.jpg](https://user-images.githubusercontent.com/33524412/195450771-bb4fe706-3728-446e-b257-8b7f9f95f25e.jpg)

**Comment by sammyke007** [comment]
Was working fine, but broken aigan. I think they are working on the API?

`Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant.config_entries
Source: custom_components/arris_dcx960/__init__.py:45
Integration: Arris DCX960 (documentation, issues)
First occurred: 10:36:21 (1 occurrences)
Last logged: 10:36:21

Error setting up entry verdonck.sammy@gmail.com for arris_dcx960
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/arris_dcx960/arrisdcx960.py", line 113, in get_oauth_session
    raise ArrisDCX960AuthenticationError("Could not get authorizationUri")
arris_dcx960.exceptions.ArrisDCX960AuthenticationError: Could not get authorizationUri

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/arris_dcx960/__init__.py", line 45, in async_setup_entry
    await hass.async_add_executor_job(api.connect)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/arris_dcx960/arrisdcx960.py", line 356, in connect
    self.get_session_and_token()
  File "/usr/local/lib/python3.10/site-packages/arris_dcx960/arrisdcx960.py", line 68, in get_session_and_token
    self.get_session()
  File "/usr/local/lib/python3.10/site-packages/arris_dcx960/arrisdcx960.py", line 74, in get_session
    self.get_oauth_session()
  File "/usr/local/lib/python3.10/site-packages/arris_dcx960/arrisdcx960.py", line 238, in get_oauth_session
    raise ArrisDCX960ConnectionError("Unknown connection failure: " + str(e))
arris_dcx960.exceptions.ArrisDCX960ConnectionError: Unknown connection failure: Could not get authorizationUri
`

**Comment by sverleysen** [comment]
I'm having the same issue with telenet

**Comment by Sholofly** [comment]
Libert global has changed the backend . I'm trying to find out what's changed and  find a solution. But time is not my friend this period so please give me some time! Thanks!

**Comment by Sholofly** [comment]
Hi there. This component is not functional anymore. I'm continuing here: https://github.com/Sholofly/lghorizon
For now only Ziggo but I'm trying to connect other providers in the future
