### ISSUE TITLE
Ziggo changed their backend?

### ISSUE THREAD

**Issue by keesg60** [Sholofly/arrisdcx960#38]
The intergration has stopped working.
The error i’m getting is:
Can’t connect
Error 401.

I’m using Ziggo NL and know for sure my login is correct.
Looks to me, Ziggo has changed their backend.

**Comment by DeadpoolW** [comment]
I have the same issue, in the logs I can see the following:

```
Logger: homeassistant.config_entries
Source: custom_components/arris_dcx960/__init__.py:45
Integration: Arris DCX960 ([documentation](https://github.com/Sholofly/arrisdcx960), [issues](https://github.com/Sholofly/arrisdcx960/issues))
First occurred: 09:54:53 (1 occurrences)
Last logged: 09:54:53

Error setting up entry wietse1988@gmail.com for arris_dcx960
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/arris_dcx960/__init__.py", line 45, in async_setup_entry
    await hass.async_add_executor_job(api.connect)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/arris_dcx960/arrisdcx960.py", line 356, in connect
    self.get_session_and_token()
  File "/usr/local/lib/python3.10/site-packages/arris_dcx960/arrisdcx960.py", line 69, in get_session_and_token
    self._get_token()
  File "/usr/local/lib/python3.10/site-packages/arris_dcx960/arrisdcx960.py", line 350, in _get_token
    jsonResult = self._do_api_call(self._api_url_token)
  File "/usr/local/lib/python3.10/site-packages/arris_dcx960/arrisdcx960.py", line 344, in _do_api_call
    raise ArrisDCX960ConnectionError(
arris_dcx960.exceptions.ArrisDCX960ConnectionError: API call failed: 404

**Comment by sammyke007** [comment]
Same for Telenet!

**Comment by ookonbekend** [comment]
> I have the same issue, in the logs I can see the following:
> 
> ```
> Logger: homeassistant.config_entries
> Source: custom_components/arris_dcx960/__init__.py:45
> Integration: Arris DCX960 ([documentation](https://github.com/Sholofly/arrisdcx960), [issues](https://github.com/Sholofly/arrisdcx960/issues))
> First occurred: 09:54:53 (1 occurrences)
> Last logged: 09:54:53
> 
> Error setting up entry wietse1988@gmail.com for arris_dcx960
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
>     result = await component.async_setup_entry(hass, self)
>   File "/config/custom_components/arris_dcx960/__init__.py", line 45, in async_setup_entry
>     await hass.async_add_executor_job(api.connect)
>   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/local/lib/python3.10/site-packages/arris_dcx960/arrisdcx960.py", line 356, in connect
>     self.get_session_and_token()
>   File "/usr/local/lib/python3.10/site-packages/arris_dcx960/arrisdcx960.py", line 69, in get_session_and_token
>     self._get_token()
>   File "/usr/local/lib/python3.10/site-packages/arris_dcx960/arrisdcx960.py", line 350, in _get_token
>     jsonResult = self._do_api_call(self._api_url_token)
>   File "/usr/local/lib/python3.10/site-packages/arris_dcx960/arrisdcx960.py", line 344, in _do_api_call
>     raise ArrisDCX960ConnectionError(
> arris_dcx960.exceptions.ArrisDCX960ConnectionError: API call failed: 404
> ```

Same issue here for ZiggoNL

**Comment by arjanvanvugt** [comment]
Yup same here ziggo NL. API call failed: 404

**Comment by JBakers** [comment]
Following this issue, because I'm experiencing the same problems. Ziggo.

Thanks.

**Comment by Sholofly** [comment]
They changed the backend indeed. I'm trying to find out what's changed and  find a solution. But time is not my friend this period so please give me some time! Thanks!

**Comment by Martinvdm** [comment]
It seems to be that Ziggo is saving the browser to saved devices. You can find youre saved devices within the control panel of the provider in 'trusted devices' section. It seems that Ziggo is saving it for 90 days as a trusted device. I will call the support this week to ask to disable the function for my account. will keep you informed.

**Comment by sammyke007** [comment]
@jsiegenthaler is working on an update/fix for his Homebridge addon at https://github.com/jsiegenthaler/homebridge-eosstb/issues/70#issuecomment-1279691243

I saw that you thanked him already in the credits, so might be less work if you can peek at his fixes ;-)

**Comment by jsiegenthaler** [comment]
@Sholofly is very welcome to peek at my code ;)

**Comment by Sholofly** [comment]
Hi there. Due to backand changes I've created a new custom component: [https://github.com/Sholofly/lghorizon/](https://github.com/Sholofly/lghorizon/). 

DISCLAIMER:

- It's not in HACS yet, So manual installation required. (it's just download and copy paste)
- **It only supports Ziggo** until I figured out the other login sequences
- It doesn't support services yet
- It doesn't support recordings yet

Submit feature requests and errors here: https://github.com/Sholofly/lghorizon/

**Comment by sammyke007** [comment]
Tnx! FYI: I'm home tomorrow if you need Telenet testing.

**Comment by Sholofly** [comment]
Thanks @sammyke007 I'm not available tomorrow but I hope I can use your test skills another day?

**Comment by sammyke007** [comment]
Offcourse!

**Comment by Sholofly** [comment]
Hi there. This component is not functional anymore. I'm continuing here: https://github.com/Sholofly/lghorizon
For now only Ziggo but I'm trying to connect other providers in the future
