### ISSUE TITLE
Nice to have; add brands icon

### ISSUE THREAD

**Issue by golles** [Sholofly/arrisdcx960#5]
If I remember correctly this is also a requirement to get your repo listed in [HACS](https://github.com/golles/default) 

But even without adding that, adding your logo to this repo, will show that on the integrations page:
https://github.com/home-assistant/brands

**Comment by Sholofly** [comment]
Thanks for you efforts!

Yeah you are right but I'm not too good in graphics. Feel free to add the icons with a PR. Should be this logo I guess: https://www.wearetfd.com/wp-content/uploads/2019/05/Arris-logo.png.

If you are good with icons but not with Git(hub) please send me the icons and I will do the PR if you like!

**Comment by golles** [comment]
Haha, I did it with the webtool suggested on that page. But I can do it

**Comment by Sholofly** [comment]
Didn't see that tools in the bottom. Doesn't look too difficult :). Thanks m8!

**Comment by golles** [comment]
[arris_dcx960.zip](https://github.com/Sholofly/arrisdcx960/files/7091809/arris_dcx960.zip)
I think this should do

**Comment by golles** [comment]
https://github.com/home-assistant/brands/pull/2785

**Comment by golles** [comment]
Above mentioned PR has been merged

**Comment by Sholofly** [comment]
That's brilliant. Thanks!
