### ISSUE TITLE
Virgin Media Ireland

### ISSUE THREAD

**Issue by iansharpecork** [Sholofly/arrisdcx960#6]
When i try to run component.
I get 'can't connect' .
User and pass is correct.

Output from logs:
Logger: custom_components.arris_dcx960.config_flow
Source: custom_components/arris_dcx960/config_flow.py:48
Integration: arrisdcx960 (documentation, issues)
First occurred: 6:30:22 PM (3 occurrences)
Last logged: 6:31:27 PM

'householdId'

**Comment by Sholofly** [comment]
Hi Ian, thanks for your feedback. I will get back to you soon as I need your input for testing.

**Comment by iansharpecork** [comment]
tried changing householdId to household_id in the const.py and it still doesnt work, if that helps

**Comment by Sholofly** [comment]
Would you mind to add 
```yaml
logs:
    ziggonext: debug
```

to your logging cnfiguration? Please send me the logs after you anonimized them.

**Comment by petethumped** [comment]
same issue here & credentials are definitely correct 

adding logging for logging **ziggonext: debug** to configuration.yaml doesn't generate any new logs when attempting to set up the integration.

adding **custom_components.arris_dcx960: debug** & attempting integration setup returns: 

2021-09-07 23:26:47 ERROR (MainThread) [custom_components.arris_dcx960.config_flow] 'householdId'

**Comment by Sholofly** [comment]
Hi,

Please remove the custom_component part from your logging line. In that way
it wel debug the underlying python package. I've changed the naming of that
package...

Ty!

Op wo 8 sep. 2021 00:35 schreef petethumped ***@***.***>:

**Comment by petethumped** [comment]
ok that's.... that's a lot of data

how much of it do you need to see?

**Comment by petethumped** [comment]
actually the first line is reporting the full details of my account, my set top boxes, and presumably my channel entitlements, so i guess it's just these lines? (I've replaced parts of the tokens with XXXXXs JUST IN CASE)

2021-09-08 21:20:03 DEBUG (SyncWorker_5) [arris_dcx960.arrisdcx960] Doing API call with url: https://prod.oesp.virginmediatv.ie/oesp/v4/IE/eng/web/tokens/jwt

2021-09-08 21:20:03 DEBUG (SyncWorker_5) [arris_dcx960.arrisdcx960] Raw result: {"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Im9lc3BfbXXXXXX.XXXXXzLWdyb3VwLWlkIjoiMTQyMjYyNjBfaWUiLCJpYXQiOjE2MzExMzI0MDMsImV4cCI6MTYzMTE1MDQwM30.XXXXXXXXX_M8AAunyASfRbsJiIqGrPav8wCefKK2hGQ"}

2021-09-08 21:20:03 DEBUG (SyncWorker_5) [arris_dcx960.arrisdcx960] Fetched a token: {'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Im9lc3BfbXXXXXX.XXXXXzLWdyb3VwLWlkIjoiMTQyMjYyNjBfaWUiLCJpYXQiOjE2MzExMzI0MDMsImV4cCI6MTYzMTE1MDQwM30.XXXXXXXXX_M8AAunyASfRbsJiIqGrPav8wCefKK2hGQ'}

**Comment by Sholofly** [comment]
It's always hard to tell. I think it's in the logs just before the error shows up.

**Comment by petethumped** [comment]
I'm not seeing anything that looks like an error in the logs, just those debug messages.

**Comment by Sholofly** [comment]
The error line from before about the household id should be there somewhere

Op do 9 sep. 2021 00:02 schreef petethumped ***@***.***>:

**Comment by petethumped** [comment]
nope, i'm not seeing that at all - the first line (the one with all my account info, boxes, and channel details) mentions householdId & references my account number with _ie appended to it a couple of times, e.g. 

'householdId': '12345678_ie'

**Comment by Sholofly** [comment]
It looks like we need to do a discord session soon. I can help you with
Debugging. Saturday evening an option?

Op do 9 sep. 2021 00:27 schreef petethumped ***@***.***>:

**Comment by Sholofly** [comment]
@petethumped Please let me know if you need any assistance..

**Comment by petethumped** [comment]
sorry, completely forgot about this!

just installed the latest version on the latest HA beta but still getting the same "Can't connect" message back, and the HA logs still show data coming back from the virginmedia.ie API

**Comment by Sholofly** [comment]
Hi there. This component is not functional anymore. I'm continuing here: https://github.com/Sholofly/lghorizon
For now only Ziggo but I'm trying to connect other providers in the future
