### ISSUE TITLE
issues during setup

### ISSUE THREAD

**Issue by steuerzentrale** [Sholofly/arrisdcx960#7]
Hi there

first of all many thanks for this nice integration. I already used ziggonext with a UPC tv box from Switzerland. The box was being recognized as a media_player entity and worked fine despite it lost connection every now and then. I was pleased to read that you created a new integration and just tried to set it up. 

**setup**
Home Assistant OS core-2021.9.2 on Raspi 4
supervisor-2021.08.1
UPC 4K box from Switzerland, energy mode set to high

**issue**
I installed the arrisdcx960 integration via HACS which worked fine. I could not find ArrisDCX960 from the integration page via Settings -> Integrations. So I configured the integration via the config.yaml file.

```
arris_dcx960:
    username: my username
    password: my password
    country_code: ch
```

Unfortunately I cant find any newly created entity of the UPC box nor any integration. What have I done wrong? I tried to follow your instructions as good as possible, reinstalled the integration and also rebooted the system as well as the UPC box.

Any help is highly appreciated

Kind regards

Andrew

**Comment by Sholofly** [comment]
Hi Andrew, thank you for reaching out. You should be able to find the integration through the UI when you've installed the component through hacs. Prior to that you should remove the yaml configuration. Is it possible to do a shared screen session using discord to find the culprit?

**Comment by Asinke** [comment]
Same issue here, unable to find the integration after removing the ziggoNext -> reboot -> install ArrisDcx960 through HACS.
Please share a solution, i'm not at home right now hence cannot support a remote session.

Arthur

**Comment by Sholofly** [comment]
Step 1:
![image](https://user-images.githubusercontent.com/901632/132094105-f2f0573b-af62-42c1-8637-80b3d9dc6e07.png)

Step2 (isn't it in this list? Then you should update HACS i think. It's in the main repo ..):
![image](https://user-images.githubusercontent.com/901632/132094131-349654ae-40b5-4572-bb51-201560b3cdd5.png)

Step3:
![image](https://user-images.githubusercontent.com/901632/132094143-8ab30129-f8c9-4552-beaa-73efea91a74f.png)

Step 4:
![image](https://user-images.githubusercontent.com/901632/132094173-b80235e8-f5a1-4f1b-8905-5d4eb9c72fea.png)

Step 5: Restart HA

Step 6:
![image](https://user-images.githubusercontent.com/901632/132094327-04be69d2-01a3-48b1-afda-93c3f6c944c9.png)

Step 7:
![image](https://user-images.githubusercontent.com/901632/132094351-20409fc0-cb6f-4650-b192-b951e394bd34.png)


Rest shoud be easy peasy :)

**Comment by JBakers** [comment]
And here also same issue.
Integration installs fine with HACS.
After server restart it does not show up when searching for arris dcx960 
![arris](https://user-images.githubusercontent.com/13487054/132094496-1313a4b8-bea6-445e-9baf-d2908d37377e.jpg)

**Comment by Sholofly** [comment]
Is there info in the logs?
Dis you remove the custom repository?

**Comment by JBakers** [comment]
Clearing the cache fixed the issue for me!

**Comment by Sholofly** [comment]
@steuerzentrale Would you like to try clearing the cache and close this isue if that fixes it?

**Comment by Asinke** [comment]
Checking again an hour later, now i was able to select and install the integration.
Install failed however with "Error running config flow", i then reinstalled/rebooted the system and setup completed succesfully.

Thanx for the great App!

**Comment by steuerzentrale** [comment]
> @steuerzentrale Would you like to try clearing the cache and close this isue if that fixes it?

Hi there

many thanks for the quick reaction. I can confirm that clearing the cache fixed the issue.
